/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WritePluginFiles {
  /**
   * a list of files.
   */
  files: {
    /**
     * the path of the file
     */
    path: string;
    /**
     * the content of the file
     */
    content: string;
  }[];
}
